# Generated by Django 4.2.3 on 2023-08-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_room_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
