# Generated by Django 4.2.3 on 2023-08-02 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_room_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='likedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
