# Generated by Django 4.2.3 on 2023-08-02 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_room_likedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='likedBy',
        ),
        migrations.AddField(
            model_name='room',
            name='likedBy',
            field=models.ManyToManyField(related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
